# See: /usr/share/doc/mpd/mpdconf.example

#pid_file "/run/mpd/mpd.pid"
pid_file "/home/daniel/.config/mpd/mpd.pid"
#db_file "/var/lib/mpd/mpd.db"
db_file "/home/daniel/.config/mpd/database"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
music_directory "/home/daniel/Music"

#database {
#    plugin "simple"
#    path "/var/lib/mpd/db"
#}
#
audio_output {
        type            "pulse"
        name            "pulse audio"
}

# audio_output {
#         type            "alsa"
#         name            "ALSA"
# }
# audio_output {
#         name            "MPD JACK output"
#         device          "jackplugmpd"
# }

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}
