[font]
size = 14.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
#family = "Hack Nerd Font Mono"
#family = "ComicShannsMono Nerd Font"
# family = "Aporetic Sans Mono"
family = "FantasqueSansM Nerd Font"
style = "Regular"

[window]
opacity = 0.8
# blur = true
dynamic_title = true

[keyboard]
bindings = [
# {key = "U", mods="Control", action="ScrollHalfPageUp"},
# {key = "D", mods="Control", action="ScrollHalfPageDown"},
# {key = "K", mods="Control", action="ScrollLineUp"},
# {key = "J", mods="Control", action="ScrollLineDown"},
]
